// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: article.proto

package server

import (
	"context"

	"zeroblog/application/article/rpc/internal/logic"
	"zeroblog/application/article/rpc/internal/svc"
	"zeroblog/application/article/rpc/pb"
)

type ArticleServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedArticleServer
}

func NewArticleServer(svcCtx *svc.ServiceContext) *ArticleServer {
	return &ArticleServer{
		svcCtx: svcCtx,
	}
}

func (s *ArticleServer) Publish(ctx context.Context, in *pb.PublishRequest) (*pb.PublishResponse, error) {
	l := logic.NewPublishLogic(ctx, s.svcCtx)
	return l.Publish(in)
}

func (s *ArticleServer) Articles(ctx context.Context, in *pb.ArticlesRequest) (*pb.ArticlesResponse, error) {
	l := logic.NewArticlesLogic(ctx, s.svcCtx)
	return l.Articles(in)
}
